### PR TITLE
(RENDERSERVICE) add cron job for cleaning cache automatically

### PR DESCRIPTION
**Pull request by Edmondi-Kacaj**
Hello @mirjan-hoffmann 

I add the possibility to delete old cache from render-service, automatically by a corn job.

### CODE REVIEW

**Comment by mirjan-hoffmann** [comment]
@Edmondi-Kacaj How does the cleanup work exactly? The process looks for the limit and only cleans up, if the limit is reached (and then the whole cache is deleted?)? Or does it cleanup everytime, but deletes just a (random) part above the limit (and stops deleting cache, if the limit is ok)?

A default period of 15 days seems a bit much to me. In 15 days the cache can quickly be full and then the system crashes. Can the default also be lowered, say daily?

**Comment by Edmondi-Kacaj** [comment]
@mirjan-hoffmann 
According to [documentation](https://docs.edu-sharing.com/confluence/edp/en/installation-en/installation-of-the-edu-sharing-rendering-service/admin-tools-cache-cleaner), The script determines the disk space consumption of the rendering service and, if it exceeds a particular threshold value - delete the resources which have not been used for the longest time from the cache. 
In the script we can adjust the constant **"RATIO_MAX"** to your liking, the default is 0.8 =80%,  which means that old objects are deleted when 80% or more of the drive space is occupied.
In the render-service Database exists a table **ESTRACK** that tracks all the objects that are converted or downloaded in the render-service server (cache data).

The default period of running the script is every 15 days (*/15), but we can adjust as we want, if we want to run the script every day we can adjust it in _**clean_cache_schedule_day**_, but it will not do anything since the script itself will check if the condition of 80% if true, if not it will do nothing. 

**_RATIO_MAX_** can also be adjusted **_esrender_cache_limit_**,

this is how the edu-sharing team implement and  use the script, I just implemented

**Comment by mirjan-hoffmann** [comment]
Thanks for the explanation.

Can you add the link to the edu-sharing documentation in your definition of the feature ([here](https://github.com/TIBHannover/edu-sharing-box/pull/17/files#diff-03eab8060c340e73102f03cad015cf179af99968019d008ceee2d1b07c9f17adR29)) - then the feature should be clear for everyone just looking at the box.

I would also say, let's reduce the default period to daily - can you adjust this?

**Comment by Edmondi-Kacaj** [comment]
@mirjan-hoffmann 

I added documentation, and also reduce the running time of the job, to every day, since it will not affect anything, It depends on the size of **RATIO_MAX ** I think is not problem if we run the job every day, we can adjust it by variable if we need it

**Review by mirjan-hoffmann — APPROVED** [review]

**Pull request merged**
