### PR TITLE
Add or modyfied custom property in alfresco extension

### PR DESCRIPTION
**Pull request by Edmondi-Kacaj**
Hello @mirjan-hoffmann 

Sometimes we need also to modify some property, so I make some adjustment in last change, now we can add, or update an existing property, also we can choose now in which file we want to make those changes

### CODE REVIEW

**Comment by mirjan-hoffmann** [comment]
Hi @Edmondi-Kacaj, This change seems to me to be impractical - you always have to set all children of an element. You must then also always set all existing children. For example, if I look at `<aspect name="ccm:iometadata">`, it means that we would have to include page-long property definitions in the configuration. We should avoid that.

Is there any other way to update properties here? For example: would it work to adjust the file not in the `shared/classes` directory, but in the freshly unpacked edu-sharing archive (current way with add-children)?

**Review by mirjan-hoffmann — CHANGES_REQUESTED** [review]
Hi @Edmondi-Kacaj, This change seems to me to be impractical - you always have to set all children of an element. You must then also always set all existing children. For example, if I look at `<aspect name="ccm:iometadata">`, it means that we would have to include page-long property definitions in the configuration. We should avoid that.

Is there any other way to update properties here? For example: would it work to adjust the file not in the `shared/classes` directory, but in the freshly unpacked edu-sharing archive (current way with add-children)?

**Comment by Edmondi-Kacaj** [comment]
Hello @mirjan-hoffmann 

Can you check now, I have fixed, this problem

**Review by mirjan-hoffmann — CHANGES_REQUESTED** [review]
Please also update the documentation for `edu_cccontentmodel_adjustments`:

```
edu-sharing-box$ grep -nR "edu_cccontentmodel_adjustments" *
...
ansible/group_vars/edusharing.yml:101:edu_cccontentmodel_adjustments:
SHIBBOLETH.md:50:edu_cccontentmodel_adjustments:
```

... and please remember to update the existing configuration after this PR is merged and included

**Comment by Edmondi-Kacaj** [comment]
Hello @mirjan-hoffmann 

I have updated also the SHIBBOLETH.md, and YES after PR I will update also existing configuration

**Review by mirjan-hoffmann — APPROVED** [review]

**Pull request merged**
