### PR TITLE
Update edu-sharing-sso-context for both, old and new edu-sharing

### PR DESCRIPTION
**Pull request by mirjan-hoffmann**
implemented the missing sso-context adjustment for new edu-sharing versions (>= 7)

### CODE REVIEW

**Comment by mirjan-hoffmann** [comment]
@Edmondi-Kacaj Could you review this please?

**Comment by Edmondi-Kacaj** [comment]
Hello @mirjan-hoffmann 

Yes, it looks Ok.

Just one thing to mention, we also so that the shibboleth **logout** does not work with the docker version, see [dfn-aai-shibboleth2.xml.j2#L91](https://github.com/TIBHannover/edu-sharing-box/blob/master/ansible/roles/shibboleth/templates/dfn-aai-shibboleth2.xml.j2#L91)

`
<Notify Channel="back" Location="http://localhost:{{tomcat_port}}/edu-sharing/services/LogoutNotification"/>
`

to something like 
`
<Notify Channel="back" Location="http://localhost:{{tomcat_port if edu_version is version_compare('7.0.0','<') else '8102' }}/edu-sharing/services/LogoutNotification"/>
`

Or we can create another pull request?

**Review by Edmondi-Kacaj — APPROVED** [review]
yes it can be taken over

**Comment by mirjan-hoffmann** [comment]
note: logout was fixed in https://github.com/TIBHannover/edu-sharing-box/commit/f191e6d52ff0ec55ee453ced09e797de3389a360

**Pull request merged**
